# Generated by Django 5.1.3 on 2025-04-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="service",
            field=models.CharField(
                choices=[
                    ("حلاقة كلاسيكية", "حلاقة كلاسيكية"),
                    ("تنظيف بشرة", "تنظيف بشرة"),
                    ("صبغة شعر", "صبغة شعر"),
                ],
                max_length=100,
            ),
        ),
    ]
